# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
