# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0006_meal_deal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
