# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0007_meal_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
