# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0008_meal_deal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_deal',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
