# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0011_auto_20190320_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_deal',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
