# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0012_auto_20190320_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_deal',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
