# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0013_auto_20190320_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_deal',
            name='picture',
        ),
    ]
