# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0016_remove_meal_deal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='pic',
            field=models.ImageField(default='uploads/None/no-img.jpeg', upload_to='uploads'),
        ),
    ]
