# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0017_meal_deal_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_deal',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
