# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0018_auto_20190321_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
