# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0022_auto_20190321_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
