# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_deal', '0023_meal_deal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_deal',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
